services:
  app:
    container_name: androxine-app-dev
    build:
      context: ../..
      dockerfile: docker/Dockerfile
    command: ./scripts/dev.sh
    env_file:
      - ../../.env.dev
    volumes:
      - ../../logs/:/app/logs/
    ports:
      - "8186:8000"

  db:
    container_name: androxine-db-dev
    ports:
      - "${DB_PORT}:5432"
