services:
  app:
    container_name: androxine-app-prod
    build:
      context: ../..
      dockerfile: docker/Dockerfile
    command: ./scripts/prod.sh
    env_file:
      - ../../.env.prod
    ports:
      - "8186:8000"

