services:
  app:
    container_name: androxine-app-test
    build:
      context: ../..
      dockerfile: docker/Dockerfile
      args:
        GROUP: "test"
    command: ./scripts/test.sh
    env_file:
      - ../../.env.test
    restart: no
